name: MAJ Auto Prix Donner

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: pip install requests pandas openpyxl

      - name: Lancer le script de scraping
        run: python donner.py

      - name: Sauvegarder le fichier Excel mis à jour
        run: |
          git config --global user.name "Bot GitHub"
          git config --global user.email "bot@users.noreply.github.com"
          git add Prix_Donner_TTC.xlsx
          git commit -m "Mise à jour automatique des prix Donner" || exit 0
          git push
